### ISSUE TITLE
[contract]: game over function

### ISSUE THREAD

**Issue by Mohiiit** [Mohiiit/flappy-bird-dojo#4]
ideally whenever the game get over, this function should get trigger. I should accept the game unique ID, score and username and save the scrore.

**Comment by ssonthal** [comment]
@Mohiiit do we need to maintain a global level array of games to store all the games? or is there another way to update the score of the game and maintain high score?

**Comment by Mohiiit** [comment]
for now let's just update the game stats? and let's think of way to get all the data, you can refer to this: https://github.com/Mugen-Space/dojo-canvas/blob/main/dojo-starter/src/systems/actions.cairo#L141 you get a mutable game and then update it, and set it again
